
version: 0.1
env:
  variables:
    S3_BUCKET: $OUTPUT_BUCKET
phases:
  install:
    commands:
      - apt-get install -y zlib1g-dev
      - pip install -r alexa/requirements.txt -t alexa/ 
      - pip install -r directors/requirements.txt -t directors/
      - pip install -r emailer/requirements.txt -t emailer/
      - pip install -r tax/requirements.txt -t tax/
      - pip install -r tax_emailer/requirements.txt -t tax_emailer/
      - pip install -r compliance/requirements.txt -t compliance/
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket $S3_BUCKET
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
