
version: 0.1
phases:
  install:
    commands:
      - apt-get update -y
      - pip install -r alexa/requirements.txt -t alexa/ 
      - pip install -r emailer/requirements.txt -t emailer/
      - pip install -r compliance_emailer/requirements.txt -t compliance_emailer/
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket aws-bids-alexa-pipeline-codepipelinebucket-1vwh6idvuy0he
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
