
version: 0.1
phases:
  install:
    commands:
      - pip install -r alexa/requirements.txt -t alexa/ 
      - pip install -r emailer/requirements.txt -t emailer/
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket awsalexaskill-pipeline-codepipelinebucket-1j5n3xexrp9tz
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
