AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Grabs services description
Parameters:
  Environment:
    Type: String
    Default: development
Resources:
  awsBidsAlexaSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: alexa/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      - AmazonSNSFullAccess
      Environment:
        Variables:
          SNS_EMAIL_TOPIC: !Ref awsBidsAlexaSns
          SNS_COMPLIANCE_TOPIC: !Ref awsBidsComplianceSns
          SNS_TAX_TOPIC: !Ref awsBidsTaxSns
          DYNAMODB_TABLE: !Ref bidsLoginTable

  awsBidsEmailerSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: emailer/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsAlexaSns

  awsBidsComplianceSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: compliance/
      Timeout: 300
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsComplianceSns

  awsBidsComplianceEmailerSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: compliance_emailer/
      Timeout: 300
      Policies:
      - AmazonS3FullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsComplianceSns

  ComplianceS3Bucket:
    Type: AWS::S3::Bucket

  awsBidsComplianceSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Compliance Topic
      TopicName: !Join ["-", [ awsBidsComplianceSns, Environment ]]

  awsBidsTaxSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: tax/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsTaxSns

  awsBidsTaxEmailerSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: tax_emailer/
      Timeout: 300
      Policies:
      - AmazonS3FullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsTaxSns

  awsBidsTaxSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Tax Topic
      TopicName: !Join ["-", [ awsBidsTaxSns, Environment ]]

  awsBidsAlexaSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Alexa Topic
      TopicName: !Join ["-", [ awsBidsAlexaSns, Environment ]]

  bidsServicesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'ServiceName'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: "ServiceName"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Join ["-", ["bidsServicesTable", Environment ]]

  bidsLoginTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Organisation"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Organisation"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "bidsLoginTable"
