AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Grabs services description
Resources:
  awsBidsAlexaSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: alexa/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      - AmazonSNSFullAccess
      Environment:
        Variables:
          SNS_TOPIC: !Ref awsBidsAlexaSns

  awsBidsEmailerSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: emailer/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsAlexaSns

  awsBidsAlexaSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Alexa Topic
      TopicName: awsBidsAlexaSns
